---
- name: Install and start Nginx
  hosts: webservers
  become: yes

  tasks:

    - name: Add epel-release repo
      yum:
         name: epel-release
         state: present
    - name: Ensure Nginx is installed
      yum:
        name: nginx
        state: latest

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
