---
- name: Install and start Apache
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHa"

    - name: Ensure Apache is running
      service:
        name: "{{ ansible_os_family == 'Debian' | ternary('apache2', 'httpd') }}"
        state: started
