---
- name: Install and start Nginx
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure Nginx is installed
      package:
        name: nginx
        state: latest

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
