name: Ansible Playbook Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no root@15.168.14.202 echo "SSH connection successful"

    - name: Validate Ansible Inventory
      run: ansible-inventory -i .ansible_inventory --list

    - name: Run Ansible Playbook
      run: ansible-playbook deploy.yml -i .ansible_inventory -vvv
